### ISSUE TITLE
Make Capacity of RuleGroup as variable or dynamic

### ISSUE THREAD

**Issue by chladic** [crowdsecurity/cs-aws-waf-bouncer#6]
Hello,

I noticed in the code plan to update hardcoded capacity. Can you please update it as temporary solution so its variable in waf_config ?
```
waf_config:
  capacity: 200
``` 
My WAF is 1200 full and I cant use it without doing any compromises

```
Capacity: aws.Int64(300), //FIXME: update it dynamically
```

Many thanks for that

**Comment by chladic** [comment]
that was super fast, amazing. Thank you

**Comment by blotus** [comment]
Hello @chladic,

A v1.0.4 including this fix has just been published in our repositories.
